apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: static-marlin-nodejs 
  janus-idp.io/tekton: static-marlin-nodejs
  backstage.io/kubernetes-id: static-marlin-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: static-marlin-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  