apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: static-marlin-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:fdf8252585e90469ab3fc4295ce21de12ae3e7b3@sha256:60eccf931f82c4a10ff4a3abd4cd56f41c1dcc0f3b404396a7e34a83d4574d38
          name: container-image
